version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/go/src/project:cached
    ports:
      - 8080:8080
    tty: true
    networks:
      local:
        aliases:
          - app.com
  admin:
    build:
      context: ./admin
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./admin:/app:cached
    tty: true
    networks:
      local:
  db:
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    networks:
      local:
networks:
  local:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.31.0.0/24
